### PR TITLE
Add support for different architecture

### LINKED ISSUE #142: Auto-detect go_arch
https://github.com/hyphacoop/cosmos-ansible/blob/main/roles/gaia/tasks/main.yml#L98

### PR DESCRIPTION
**Pull request by YurkoWasHere**
Fixes #142 

Added map for linux arch = binary name and auto selection of go arch binary (go_arch)

Closes #143 as well

### CODE REVIEW

**Comment by dasanchez** [comment]
Could we use this architecture variable for downloading the right binary releases as well?
https://github.com/hyphacoop/cosmos-ansible/blob/7f28a4d6fcd1e0bdbf97ce99cfed01bbd852b525/roles/gaia/defaults/main.yml#L10

**Comment by YurkoWasHere** [comment]
> @YurkoWasHere could we use this architecture variable for downloading the right binary releases as well?

Yep,
Problem with atomic PRs, dependencies :) Would have been better if 143 would be merged before 138 :P
https://github.com/hyphacoop/cosmos-ansible/issues/122#issuecomment-119099a4489

**Comment by YurkoWasHere** [comment]
Merged main into this branch
https://github.com/hyphacoop/cosmos-ansible/pull/143/commits/a1535021fddd7951d7f5864fa8940f8cc7a81963

Then added support for binary file arch
https://github.com/hyphacoop/cosmos-ansible/pull/143/commits/a3e0119f75677ae46ee46085c71a5e9efdbac793

**Review by dasanchez — APPROVED** [review]
✔ Ran [Join Theta Testnet workflow](https://github.com/hyphacoop/cosmos-ansible/actions/runs/2725603981)

Tested `examples/inventory-theta.yml` on amd64 target:
- ✔ as-is
- ✔ with `gaiad_binary_source: "release"`

Thanks @YurkoWasHere!

**Pull request merged**
